import { Paletts } from '../interfaces';

export const paletts: Paletts[] = [
  {
    id: 1,
    uid: 5,
    title: 'Casual',
    colors: [
      { hex: '#4f6a8f', removable: false },
      { hex: '#88a2bc', removable: false },
      { hex: '#f0dbb0', removable: false },
      { hex: '#efb680', removable: false },
      { hex: '#d99477', removable: false },
    ],
    removable: false,
  },
  {
    id: 2,
    uid: 5,
    title: 'Sunset',
    colors: [
      { hex: '#3e9cbf', removable: false },
      { hex: '#a7ecf2', removable: false },
      { hex: '#f2c43d', removable: false },
      { hex: '#f17c37', removable: false },
      { hex: '#f26d50', removable: false },
    ],
    removable: false,
  },
  {
    id: 3,
    uid: 5,
    title: 'Outrun',
    colors: [
      { hex: '#fffc40', removable: false },
      { hex: '#faba61', removable: false },
      { hex: '#ff8172', removable: false },
      { hex: '#ff2fa9', removable: false },
      { hex: '#3a579a', removable: false },
      { hex: '#36244f', removable: false },
    ],
    removable: false,
  },
  {
    id: 4,
    uid: 5,
    title: 'Raspberry',
    colors: [
      { hex: '#730517', removable: false },
      { hex: '#f44560', removable: false },
      { hex: '#44d1df', removable: false },
      { hex: '#32a4a7', removable: false },
      { hex: '#1e7069', removable: false },
    ],
    removable: false,
  },
  {
    id: 5,
    uid: 5,
    title: 'Pop',
    colors: [
      { hex: '#00ff3f', removable: false },
      { hex: '#35b5ff', removable: false },
      { hex: '#ff479c', removable: false },
      { hex: '#fffb38', removable: false },
    ],
    removable: false,
  },
  {
    id: 6,
    uid: 5,
    title: 'Cathode',
    colors: [
      { hex: '#a8216b', removable: false },
      { hex: '#f1184c', removable: false },
      { hex: '#f36943', removable: false },
      { hex: '#f7dc66', removable: false },
      { hex: '#2e9599', removable: false },
    ],
    removable: false,
  },
  {
    id: 7,
    uid: 5,
    title: 'Bubblegum',
    colors: [
      { hex: '#f8cd82', removable: false },
      { hex: '#f65b74', removable: false },
      { hex: '#f72078', removable: false },
      { hex: '#23b0bd', removable: false },
      { hex: '#0df7db', removable: false },
    ],
    removable: false,
  },
  {
    id: 8,
    uid: 5,
    title: 'Night at the Beach',
    colors: [
      { hex: '#262335', removable: false },
      { hex: '#503c52', removable: false },
      { hex: '#9f6c66', removable: false },
      { hex: '#d4896a', removable: false },
      { hex: '#ffbb6c', removable: false },
    ],
    removable: false,
  },
  {
    id: 9,
    uid: 5,
    title: 'Spectral',
    colors: [
      { hex: '#471337', removable: false },
      { hex: '#b13254', removable: false },
      { hex: '#ff5349', removable: false },
      { hex: '#ff7249', removable: false },
      { hex: '#ff9248', removable: false },
    ],
    removable: false,
  },
  {
    id: 10,
    uid: 5,
    title: 'Patagonia',
    colors: [
      { hex: '#202e32', removable: false },
      { hex: '#85937a', removable: false },
      { hex: '#586c5c', removable: false },
      { hex: '#a9af90', removable: false },
      { hex: '#dfdcb9', removable: false },
    ],
    removable: false,
  },
  {
    id: 11,
    uid: 5,
    title: 'Midnight',
    colors: [
      { hex: '#010c1e', removable: false },
      { hex: '#001e38', removable: false },
      { hex: '#4a6d88', removable: false },
      { hex: '#c6cdd7', removable: false },
      { hex: '#d5d9e0', removable: false },
    ],
    removable: false,
  },
  {
    id: 12,
    uid: 5,
    title: 'Newsstand',
    colors: [
      { hex: '#ffffff', removable: false },
      { hex: '#e7c892', removable: false },
      { hex: '#f2f2f3', removable: false },
      { hex: '#bdeefb', removable: false },
      { hex: '#88d9d0', removable: false },
      { hex: '#000000', removable: false },
    ],
    removable: false,
  },
  {
    id: 13,
    uid: 5,
    title: 'Springfield',
    colors: [
      { hex: '#89d1dc', removable: false },
      { hex: '#f89cfa', removable: false },
      { hex: '#c386f1', removable: false },
      { hex: '#f0d689', removable: false },
      { hex: '#aff28b', removable: false },
    ],
    removable: false,
  },
  {
    id: 14,
    uid: 6,
    title: 'CGA',
    colors: [
      { hex: '#000000', removable: true },
      { hex: '#0000a8', removable: true },
      { hex: '#00a800', removable: true },
      { hex: '#00a8a8', removable: true },
      { hex: '#a80000', removable: true },
      { hex: '#a800a8', removable: true },
      { hex: '#a85400', removable: true },
      { hex: '#a8a8a8', removable: true },
      { hex: '#545454', removable: true },
      { hex: '#5354fd', removable: true },
      { hex: '#54fd54', removable: true },
      { hex: '#54fefe', removable: true },
      { hex: '#fd5453', removable: true },
      { hex: '#fe53fd', removable: true },
      { hex: '#fdfc53', removable: true },
      { hex: '#fcfcfe', removable: true },
    ],
    removable: true,
  },
  {
    id: 15,
    uid: 6,
    title: 'LCD',
    colors: [
      { hex: '#0f370e', removable: true },
      { hex: '#30622f', removable: true },
      { hex: '#8bad0d', removable: true },
      { hex: '#9bbc0e', removable: true },
    ],
    removable: true,
  },
  {
    id: 16,
    uid: 6,
    title: 'PICO-8',
    colors: [
      { hex: '#000000', removable: true },
      { hex: '#1d2b53', removable: true },
      { hex: '#7e2453', removable: true },
      { hex: '#008751', removable: true },
      { hex: '#ab5236', removable: true },
      { hex: '#5f574e', removable: true },
      { hex: '#c2c3c7', removable: true },
      { hex: '#fff2e9', removable: true },
      { hex: '#ff004d', removable: true },
      { hex: '#ffa300', removable: true },
      { hex: '#ffec27', removable: true },
      { hex: '#00e536', removable: true },
      { hex: '#29aeff', removable: true },
      { hex: '#83769c', removable: true },
      { hex: '#ff77a8', removable: true },
      { hex: '#ffcdaa', removable: true },
    ],
    removable: true,
  },
];
